name: Wayback Machine
description: Save the provided sites to the Wayback Machine at archive.org

inputs:
  source:
    description: “The site handle to screenshot”
    required: true
  command:
    description: "The wayback.py command to run"
    required: true
  access-key:
    description: An API key with permission to post to archive.org
    required: true
  secret-key:
    description: An API secret with permission to post to archive.org
    required: true

runs:
  using: "composite"
  steps:
    - id: install-apt-packages
      name: Install apt packages
      run: |
        sudo apt-get update
        sudo apt install -y curl
      shell: bash

    - id: save-page
      name: Save in Wayback Machine
      run: pipenv run python -m newshomepages.wayback ${{ inputs.command }} ${{ inputs.source }}
      shell: bash
      env:
        IA_ACCESS_KEY: ${{ inputs.access-key }}
        IA_SECRET_KEY: ${{ inputs.secret-key }}
