name: Screenshot
description: Snap a JPG of the provided site

inputs:
  source:
    description: “The site handle to screenshot”
    required: true
  command:
    description: "The tweet.py command to run"
    required: true

runs:
  using: "composite"
  steps:
    - id: install-apt-packages
      name: Install apt packages
      run: |
        sudo apt-get update
        sudo apt install -y ubuntu-restricted-extras ffmpeg libavcodec-extra
      shell: bash

    - id: cache-playwright
      name: Cache Playwright browsers
      uses: actions/cache@v2
      with:
        path: ~/.cache/ms-playwright/
        key: ${{ runner.os }}-browsers

    - id: install-playwright
      name: Install Playwright dependencies
      run: pipenv run shot-scraper install --browser=chrome
      shell: bash

    - id: shoot
      name: Take screenshot
      run: pipenv run python -m newshomepages.shoot ${{ inputs.command }} ${{ inputs.source }} -o _dist
      shell: bash

    - id: save
      name: Save artifact
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: _dist
        if-no-files-found: error
