name: Telegram
description: Post screenshots to Telegram of the provided site

inputs:
  source:
    description: “The site handle to screenshot”
    required: true
  command:
    description: "The telegrammer.py command to run"
    required: true
  api-key:
    description: An API key with permission to post to Telegram
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: screenshots

    - id: list
      name: List
      run: ls -alF
      shell: bash

    - id: telegram
      name: Telegram
      run: pipenv run python -m newshomepages.telegrammer ${{ inputs.command }} ${{ inputs.source }}
      shell: bash
      env:
        TELEGRAM_API_KEY: ${{ inputs.api-key }}
