name: Commit
description: Save the latest screenshots to the repository

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: screenshots
        path: ./latest-screenshots

    - id: list
      name: List
      run: ls -alF ./latest-screenshots
      shell: bash

    - name: Commit and push
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Saved latest screenshots
        file_pattern: ./latest-screenshots/*.jpg
