inputs:
  source:
    description: “The site handle to screenshot”
    required: true
  command:
    description: "The hyperlinks.py command to run"
    required: true

runs:
  using: "composite"
  steps:
    - id: cache-playwright
      name: Cache Playwright browsers
      uses: actions/cache@v2
      with:
        path: ~/.cache/ms-playwright/
        key: ${{ runner.os }}-browsers

    - id: install-playwright
      name: Install Playwright dependencies
      run: pipenv run shot-scraper install
      shell: bash

    - id: parse-json
      name: Parse out hyperlinks
      run: pipenv run python -m newshomepages.hyperlinks ${{ inputs.command }} ${{ inputs.source }} -o _dist
      shell: bash

    - id: save
      name: Save artifact
      uses: actions/upload-artifact@v2
      with:
        name: hyperlinks
        path: _dist
        if-no-files-found: error
