name: Discord
description: Post screenshots to a Discord channel

inputs:
  source:
    description: “The site handle to screenshot”
    required: true
  command:
    description: "The telegrammer.py command to run"
    required: true
  bot-token:
    description: A bot token with permission to post to Discord
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: screenshots

    - id: discord
      name: Discord
      run: pipenv run python -m newshomepages.discorder ${{ inputs.command }} ${{ inputs.source }}
      shell: bash
      env:
        DISCORD_BOT_TOKEN: ${{ inputs.bot-token }}
