name: Bundle Screenshot

on:
  workflow_call:
    inputs:
      source:
        description: "The bundle slug to screenshot"
        required: true
        type: string
    secrets:
      telegram-api-key:
        description: An API key with permission to post to Telegram
        required: true
      discord-bot-token:
        description: A bot token with permission to post to Discord
        required: true
      twitter-consumer-key:
        description: A Twitter user consumer key
        required: true
      twitter-consumer-secret:
        description: A Twitter user consumer secret
        required: true
      twitter-access-token-key:
        description: A Twitter app access token key
        required: true
      twitter-access-token-secret:
        description: A Twitter app access token secret
        required: true
      ia-access-key:
        description: An API key with permission to post to archive.org
        required: true
      ia-secret-key:
        description: An API secret with permission to post to archive.org
        required: true
      ia-collection:
        description: The identifier of the target archive.org collection
        required: true

jobs:
  jpg:
    name: JPG
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: install
        name: Install
        uses: ./.github/actions/install

      - id: screenshot
        name: Screenshot
        uses: ./.github/actions/screenshot
        with:
          source: ${{ inputs.source }}
          command: bundle

  accessibility:
    name: Accessibility tree
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: install
        name: Install
        uses: ./.github/actions/install

      - id: save-page
        name: Save the accessibility tree
        uses: ./.github/actions/accessibility
        with:
          source: ${{ inputs.source }}
          command: bundle

  hyperlinks:
    name: Hyperlinks
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: install
        name: Install
        uses: ./.github/actions/install

      - id: save-page
        name: Save hyperlinks
        uses: ./.github/actions/hyperlinks
        with:
          source: ${{ inputs.source }}
          command: bundle

  wayback:
    name: Wayback Machine
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: install
        name: Install
        uses: ./.github/actions/install

      - id: save-page
        name: Save in Wayback Machine
        uses: ./.github/actions/wayback
        with:
          source: ${{ inputs.source }}
          command: bundle

  twitter:
    name: Post to Twitter
    needs: [jpg]
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: install
        name: Install
        uses: ./.github/actions/install

      - id: tweet
        name: Post
        uses: ./.github/actions/tweet
        with:
          source: ${{ inputs.source }}
          command: bundle
          consumer-key: ${{ secrets.twitter-consumer-key }}
          consumer-secret: ${{ secrets.twitter-consumer-secret }}
          access-token-key: ${{ secrets.twitter-access-token-key }}
          access-token-secret: ${{ secrets.twitter-access-token-secret }}

  telegram:
    name: Post to Telegram
    needs: [jpg]
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: install
        name: Install
        uses: ./.github/actions/install

      - id: telegram
        name: Post
        uses: ./.github/actions/telegram
        with:
          source: ${{ inputs.source }}
          command: bundle
          api-key: ${{ secrets.telegram-api-key }}

  discord:
    name: Post to Discord
    needs: [jpg]
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: install
        name: Install
        uses: ./.github/actions/install

      - id: discord
        name: Post
        uses: ./.github/actions/discord
        with:
          source: ${{ inputs.source }}
          command: bundle
          bot-token: ${{ secrets.discord-bot-token }}

  archive:
    name: Post to archive.org
    needs: [jpg,accessibility]
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: install
        name: Install
        uses: ./.github/actions/install

      - id: archive
        name: Post
        uses: ./.github/actions/archive
        with:
          source: ${{ inputs.source }}
          command: bundle
          access-key: ${{ secrets.ia-access-key }}
          secret-key: ${{ secrets.ia-secret-key }}
          collection: ${{ secrets.ia-collection }}
