name: Single Screenshot

on:
  workflow_call:
    inputs:
      source:
        description: "The site handle to screenshot"
        required: true
        type: string
    secrets:
      telegram-api-key:
        description: An API key with permission to post to Telegram
        required: true
      discord-bot-token:
        description: A bot token with permission to post to Discord
        required: true
      twitter-consumer-key:
        description: A Twitter user consumer key
        required: true
      twitter-consumer-secret:
        description: A Twitter user consumer secret
        required: true
      twitter-access-token-key:
        description: A Twitter app access token key
        required: true
      twitter-access-token-secret:
        description: A Twitter app access token secret
        required: true
      ia-access-key:
        description: An API key with permission to post to archive.org
        required: true
      ia-secret-key:
        description: An API secret with permission to post to archive.org
        required: true
      ia-collection:
        description: The identifier of the target archive.org collection
        required: true

jobs:
  jpg:
    name: Capture JPG
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        source: ${{fromJson(inputs.source)}}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: install
        name: Install
        uses: ./.github/actions/install

      - id: screenshot
        name: Screenshot
        uses: ./.github/actions/screenshot
        with:
          source: ${{ matrix.source }}
          command: single

  accessibility:
    name: Accessibility tree
    runs-on: ubuntu-latest
    strategy:
      matrix:
        source: ${{fromJson(inputs.source)}}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: install
        name: Install
        uses: ./.github/actions/install

      - id: save-page
        name: Save the accessibility tree
        uses: ./.github/actions/accessibility
        with:
          source: ${{ matrix.source }}
          command: single

  wayback:
    name: Wayback Machine
    runs-on: ubuntu-latest
    strategy:
      matrix:
        source: ${{fromJson(inputs.source)}}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: install
        name: Install
        uses: ./.github/actions/install

      - id: save-page
        name: Save in Wayback Machine
        uses: ./.github/actions/wayback
        with:
          source: ${{ matrix.source }}
          command: single

  twitter:
    name: Post to Twitter
    needs: [jpg]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        source: ${{fromJson(inputs.source)}}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: install
        name: Install
        uses: ./.github/actions/install

      - id: tweet
        name: Post
        uses: ./.github/actions/tweet
        with:
          source: ${{ matrix.source }}
          command: single
          consumer-key: ${{ secrets.twitter-consumer-key }}
          consumer-secret: ${{ secrets.twitter-consumer-secret }}
          access-token-key: ${{ secrets.twitter-access-token-key }}
          access-token-secret: ${{ secrets.twitter-access-token-secret }}

  telegram:
    name: Post to Telegram
    needs: [jpg]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        source: ${{fromJson(inputs.source)}}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: install
        name: Install
        uses: ./.github/actions/install

      - id: telegram
        name: Post
        uses: ./.github/actions/telegram
        with:
          source: ${{ matrix.source }}
          command: single
          api-key: ${{ secrets.telegram-api-key }}

  discord:
    name: Post to Discord
    needs: [jpg]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        source: ${{fromJson(inputs.source)}}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: install
        name: Install
        uses: ./.github/actions/install

      - id: discord
        name: Post
        uses: ./.github/actions/discord
        with:
          source: ${{ matrix.source }}
          command: single
          bot-token: ${{ secrets.discord-bot-token }}

  archive:
    name: Post to archive.org
    needs: [jpg]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        source: ${{fromJson(inputs.source)}}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: install
        name: Install
        uses: ./.github/actions/install

      - id: archive
        name: Post
        uses: ./.github/actions/archive
        with:
          source: ${{ matrix.source }}
          command: single
          access-key: ${{ secrets.ia-access-key }}
          secret-key: ${{ secrets.ia-secret-key }}
          collection: ${{ secrets.ia-collection }}

  commit:
    name: Commit
    needs: [jpg]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        source: ${{fromJson(inputs.source)}}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: commit
        name: Commit
        uses: ./.github/actions/commit
